pref("extensions.firerobot.enabled-locators", "id,name,href,link,alt,src,value,label,index,xpath");
pref("extensions.firerobot.window-mode", "sidebar");
pref("extensions.firerobot.variables.create", true);
pref("extensions.firerobot.variables.use", true);
pref("extensions.firerobot.variables.create-for-loc", false);
pref("extensions.firerobot.variables.use-for-loc", false);
pref("extensions.firerobot.key.replace", true);
pref("extensions.firerobot.key.target", "self");
pref("extensions.firerobot.key.res_file", "");
